### ISSUE TITLE
Create parameter or session cookie to start/end sessions

### ISSUE THREAD

**Issue by bstavenuiter** [socialblue/laravel-query-adviser#120]
Maybe it is interesting to start and end sessions by either passing in a query parameter. 

Or maybe by installing a chrome extension (just like xdebug)

This would make it easier for users to start sessions without leaving the tab they are currently in.

**Comment by mbroersen** [comment]
Thanks, Bart for your suggestion. I'm currently working on a chrome dev tools extension for Laravel Query Adviser.
Hope to release this improvement very soon :).

**Comment by mbroersen** [comment]
@bstavenuiter just released the [chrome plugin](https://chrome.google.com/webstore/detail/laravel-query-adviser/dgojkgibloeebbjieckfjaflodkamdbf) for laravel query adviser.
