### ISSUE TITLE
Escape characters are not shown with in the query adviser, so can't re-run the query.

### ISSUE THREAD

**Issue by Mirnaxvb** [socialblue/laravel-query-adviser#29]
When you have a query, that uses an namespaces for example. It will not escape the \ character so if you re-run the query it won't give any results

`
$query->where('notifications.notifiable_type', [User::class])
`

Results in:

`
notifications.notifiable_type = 'App\Model\User'
`

Perhaps this is not an issue in the package, but i should use https://www.php.net/manual/en/function.addslashes.php instead.

**Comment by mbroersen** [comment]
It looks like the pdo->quote function removes the slashes I will try to fix this one. 
thanks for reporting this one :)
